spring:
  application:
    name: Crafty
  config:
    import: optional:file:./secrets.properties

  datasource:
    url: jdbc:postgresql://localhost:5432/craftydb?serverTimezone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
#          model: x-ai/grok-code-fast-1
          # model: google/gemini-3-flash-preview
          model: openrouter/free
          temperature: 0.3
jwt:
  secret-key: ${JWT_SECRET_KEY}

stripe:
  api:
    secret: ${STRIPE_API_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

client.url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects
